version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: mock
      POSTGRES_PASSWORD: mock123
      POSTGRES_DB: mockdb
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data